# Build our Docker container and R pkg on Travis

env:
  global:
  - REPO=$DOCKER_USER/rice_awd_pests

sudo: required

warnings_are_errors: false

language: R

services:
  - docker

before_install:
  - sudo apt-get install r-base-core
    # create & run container using our dockerfile, i.e. compile pkg and render Rmd to PDF
  - docker build -t $REPO .

# push our custom docker container to docker hub, env vars stored on travis-ci.org
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/rice_awd_pests
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
