# Build our Docker container and R pkg on Travis

env:
  global:
  - REPO=$DOCKER_USER/rice_awd_pests

sudo: required

warnings_are_errors: false

language: generic

services:
  - docker

before_install:
    # create & run container using our dockerfile, i.e. compile pkg and render Rmd to PDF
  - docker build -t $REPO .

# push our custom docker container to docker hub, env vars stored on travis-ci.org
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/rice_awd_pests
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
