---
title: "Test Residuals for Model Fits"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ProjectTemplate)
load.project()
```

```{r}
require(car)
require(MASS)

# This is so that distributions that must be non-zero can make sense of my
# data
AUDPS_15 <- subset(AUDPS, YEAR == 2015)
AUDPS_16 <- subset(AUDPS, YEAR == 2016)

qqp(AUDPS_15$LShB_percent_AUDPS, "norm")
qqp(AUDPS_15$LShB_percent_AUDPS, "lnorm")
qqp(AUDPS_15$LShB_percent_AUDPS, "exp")
qqp(AUDPS_15$LShB_percent_AUDPS, "chisq", df = 2)

qqp(AUDPS_16$LShB_percent_AUDPS, "norm")
qqp(AUDPS_16$LShB_percent_AUDPS, "lnorm")
qqp(AUDPS_16$LShB_percent_AUDPS, "exp")
qqp(AUDPS_16$LShB_percent_AUDPS, "chisq", df = 2)

qqp(AUDPS_15$TShB_percent_AUDPS, "norm")
qqp(AUDPS_15$TShB_percent_AUDPS, "lnorm")
qqp(AUDPS_15$TShB_percent_AUDPS, "exp")
qqp(AUDPS_15$TShB_percent_AUDPS, "chisq", df = 2)

qqp(AUDPS_16$TShB_percent_AUDPS, "norm")
qqp(AUDPS_16$TShB_percent_AUDPS, "lnorm")
qqp(AUDPS_16$TShB_percent_AUDPS, "exp")
qqp(AUDPS_16$TShB_percent_AUDPS, "chisq", df = 2)

qqp(AUDPS_15$TShB_inc_AUDPS, "norm")
qqp(AUDPS_15$TShB_inc_AUDPS, "lnorm")
qqp(AUDPS_15$TShB_inc_AUDPS, "exp")
qqp(AUDPS_15$TShB_inc_AUDPS, "chisq", df = 2)

qqp(AUDPS_16$TShB_inc_AUDPS, "norm")
qqp(AUDPS_16$TShB_inc_AUDPS, "lnorm")
qqp(AUDPS_16$TShB_inc_AUDPS, "exp")
qqp(AUDPS_16$TShB_inc_AUDPS, "chisq", df = 2)
```
