---
title: Do Alternate Wetting and Drying Irrigation Technology and Nitrogen Rates Affect Rice Sheath Blight?
author: |
  | Adam H. Sparks 1^[Corresponding author: Adam.Sparks@usq.edu.au]  \textsuperscript{1, \dag}, Nancy P. Castilla \textsuperscript{1}, Bjorn Ole Sander \textsuperscript{1}
  | \textsuperscript{1}International Rice Research Institute, Crop and Environmental Sciences Divsion, Los Baños, Laguna, Philippines, 4031 \newline \textsuperscript{\dag} Current Address: University of Southern Queensland, Centre for Crop Health, West Street, Tooowoomba, Queensland, Australia, 4350
abstract: |
  Water and nitrogen management play vital roles in rice production. However, the mismanagement of these two management practices may trigger sheath blight of rice, caused by _Rhizoctonia solani_, which is favored by wet conditions, high relative humidity, and high nitrogen fertilizer levels. To understand how different combinations of water and nitrogen management affect sheath blight epidemics, we conducted two separate split-plot experiments with a water saving (alternate wetting and drying) regime and traditional flood irrigation regime combined with differing nitrogen treatments in the dry seasons of 2015 and 2016. Disease was scored in the same way in both experiments using a sheath blight assessment scale for field evaluation developed at the International Rice Research Institute to assess the severity on infected sheaths and leaves while sheath blight incidence on tillers were counted per hill. We were unable to detect any differences in disease in either experiment due to irrigation regime, N rates or the interaction of the two treatments in either season. This suggests that farmers can adopt water saving technologies without risking increased sheath blight incidence. We suggest that further cross-cutting research in this area is warranted.

bibliography: references.bib
output:
  bookdown::pdf_document2:
    toc: no
fig_caption: yes

always_allow_html: yes

# These are LaTex settings to take care of floating figures/tables, line spacing, etc
header-includes:
  - \usepackage{endfloat}
  - \usepackage{setspace}\doublespacing
  - \usepackage{lineno}
  - \linenumbers
---

```{r Setup..., message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(fig.pos = "p") # Places figures on their own pages
knitr::opts_chunk$set(out.width = "100%", dpi = 300)

library(bookdown)
library(knitr)
library(kableExtra)
```

# Introduction

Alternate wetting and drying (AWD) is an irrigation technique for irrigated rice developed by the International Rice Research Institute (IRRI) and its partners that saves about 15-40% of irrigation water [@Bouman2001; @Feng2007]. In AWD rice fields are exposed to several dry phases during the growth period without exposing the plants to water stress. In order to avoid yield decline under AWD “safe” thresholds have been developed. Under safe AWD irrigation water is applied when the field water level reaches 15cm below the soil surface [@Richards2014]. Fields are furthermore kept flooded during the flowering period. Besides saving water AWD also reduces greenhouse gas (GHG) emissions of rice fields, which is a substantial factor in the GHG budget of rice producing countries, by around 50% [@Yan2005; @Sander2015].

The AWD technology has been identified as promising climate smart practice for different rice growing regions that can stabilize rice production in water scarce areas as well as help reduce the carbon footprint of rice production. Various countries, \textit{e.g.}, Bangladesh, Vietnam, Thailand and the Philippines, plan to widely apply AWD to local rice production [@MOEF2015]. However, a change in water regime in rice fields on large scale might encompass different other effects, for example related to plant health.

We therefore established field experiments in order to…

# Materials and Methods

## Experimental design

Two experiments were conducted at the International Rice Research Institute's (IRRI) Ziegler Experiment Station in Los Baños, Calabarzon, Philippines (latitude 14&deg; 11' N, , longitude 121&deg; 15' E) in the 2015 and 2016 dry seasons. For the 2016 season changes were made to optimize the experiment based on findings from the 2015 season. Both seasons consisted of split plot design with four replicates where irrigation was the main plot and nitrogen (N) rate was the split plot treatment. The changes between seasons and experiments are detailed following.

### 2015 Dry Season

The main plot size was 12m x 12m (144 sq m), with a sub-plot size of 5m x 5m (25 sq m). Replication size was 12m x 24m (288 sq m) with a buffer of 1m per sub plot for a whole experiment size of 1,152 sq m. The main plot treatments were alternate wetting and drying (AWD) and ) and continuously flooded (CF) or farmers' practice.

Irrigation in AWD plots was determined by the water level in plots, i.e., when the water level reached 15cm below the soil surface irrigation water was applied to a level of 5cm. In CF plots a standing water layer of 3-5cm was maintained throughout the growing season. 

The subplot treatments were different rates of nitrogen…

The plots were inoculated using...


### 2016 Dry Season

In 2016 dry season the plot size was increased and due to these changes, the sizes of the replicates are not equal as necessitated by the use of a larger area for the experiment. The main plot sizes were: Block 1 (B1) 21m x 20.5m (412.5 sq m) and Block 2 (B2) 20.25m x 21.6m (437.4 sq m). The sub plot sizes were B1 21m x 10.25m (215.25 sq m), B2 20.25m x 10.8m (218.7 sq m). The replication sizes were B1 - 42m x 20.5m (861 sq m) and B2 - 40.5m x 21.6m (874.8 sq m). A buffer 0.5m per sub plot was used and the overall experiment size was 3471.6 sq m.

The plots were inoculated using...

## Data collection and analysis

Disease scoring was the same in both experiments using a sheath blight assessment scale for field evaluation developed at IRRI to assess the severity on infected sheaths and leaves while sheath blight incidence on tillers were counted per hill. Five and four disease assessments were made in 2015 and 2016, respectively.

Disease severity was converted to area under the disease progress stairs (AUDPS) [@simko2012area] and analysed using multivariate generalised linear mixed models implemented in the MCMCglmm package [@MCMCglmm2017] in R [@R2017].

# Results

# Discussion

# Acknowledgments

# References {#references .unnumbered}

Supporting information captions (if applicable)
