---
title: "Do Alternate Wetting and Drying Irrigation Technologies and Nitrogen Rates Affect Rice Sheath Blight?"
thanks: "Replication files are available on the author's Github account (http://github.com/adamhsparks/AWD_N_SB). **Current version**: `r format(Sys.time(), '%B %d, %Y')`; **Corresponding author**: Adam.Sparks@usq.edu.au"
author:
  - A.H. Sparks and N.P. Castilla and B.O. Sander
keywords: "_Rhizoctonia solani_, Irrigation"
abstract: "First author: University of Southern Queensland, Centre for Crop Health, West St., Toowoomba, Queensland 4350, Australia; and second and third authors: International Rice Research Institute, Crop and Environmental Sciences Division, Los Baños, Laguna 4031, Philippines."
output:
  word_document:
    keep_md: yes
    reference_docx: Phytopathology_Style_Reference.docx
  html_document: default
csl: phytopathology.csl
bibliography: AWD_N_ShB.bib
---

Corresponding author: Adam H. Sparks; E-mail address: Adam.Sparks@usq.edu.au

______

# Abstract

Water and nitrogen management play vital roles in rice production. However, the mismanagement of these two management practices may trigger sheath blight of rice, caused by _Rhizoctonia solani_, which is favored by wet conditions, high relative humidity, and high nitrogen fertilizer levels. To understand how different combinations of water and nitrogen management affect sheath blight epidemics, we conducted two separate split-plot experiments with a water saving (alternate wetting and drying) regime and traditional flood irrigation regime combined with differing nitrogen treatments in the dry seasons of 2015 and 2016. Disease was scored in the same way in both experiments using a sheath blight assessment scale for field evaluation developed at the International Rice Research Institute to assess the severity on infected sheaths and leaves while sheath blight incidence on tillers were counted per hill. We were unable to detect any differences in disease in either experiment due to irrigation regime, N rates or the interaction of the two treatments in either season. This suggests that farmers can adopt water saving technologies without risking increased sheath blight incidence. We suggest that further cross-cutting research in this area is warranted. 

______

#####

# Materials and Methods
## Experimental design
Two experiments were conducted at the International Rice Research Institute's (IRRI) Ziegler Experiment Station in Los Baños, Calabarzon, Philippines (latitude 14°11' N, , longitude 121°15' E) in the 2015 and 2016 dry seasons. For the 2016 season changes were made to optimize the experiment based on findings from the 2015 season. Both seasons consisted of split plot design with four replicates where irrigation was the main plot and nitrogen (N) rate was the split plot treatment. The changes between seasons and experiments are detailed following.

### 2015 Dry Season
The main plot size was 12m x 12m (144 sq m), with a sub-plot size of 5m x 5m (25 sq m). Replication size was 12m x 24m (288 sq m) with a buffer of 1m per sub plot for a whole experiment size of 1,152 sq m. The main plot treatments were alternate wetting and drying (AWD) and flooded or farmers' practice.

### 2016 Dry Season
In 2016 dry season the plot size was increased and due to these changes, the sizes of the replicates are not equal as necessitated by the use of a larger area for the experiment. The main plot sizes were: Block 1 (B1) 21m x 20.5m (412.5 sq m) and Block 2 (B2) 20.25m x 21.6m (437.4 sq m). The sub plot sizes were B1 21m x 10.25m (215.25 sq m), B2 20.25m x 10.8m (218.7 sq m). The replication sizes were B1 - 42m x 20.5m (861 sq m) and B2 - 40.5m x 21.6m (874.8 sq m). A buffer 0.5m per sub plot was used and the overall experiment size was 3471.6 sq m.

## Data collection and analysis

Data were analysed using multivariate generalised linear mixed models implemented in the MCMCglmm package [@MCMCglmm2017] in R [@R2017].

# Results


# Discussion


# Acknowledgments


# Literature Cited
