name: Docker registry
on: [push]
jobs:
  build:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      ‐ name: build-push
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: adamhsparks/rice-awd-shb
          tags: latest
