name: Docker registry

on: [push]

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v1.1.0

      - name: Build and push :latest
        if: success()
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: adamhsparks/rice-awd-shb
            tag_with_ref: true
            tag_with_sha: true
